---
title: "Survey analysis"
author: "Keith McNulty"
date: "7/5/2021"
output: html_document
---

```{r, eval = FALSE, echo = FALSE}
library(tidyverse)

map_5levels <- function(x) {
  dplyr::case_when(
    tolower(x) == "strongly disagree" ~ 1,
    tolower(x) == "disagree" ~ 2,
    tolower(x) == "neither agree nor disagree" ~ 3,
    tolower(x) == "agree" ~ 4,
    tolower(x) == "strongly agree" ~ 5,
    TRUE ~ NA_real_
  )
}

map_3levels1 <- function(x) {
  dplyr::case_when(
    x == "Beginner" ~ 1,
    x == "Intermediate" ~ 2,
    x == "Advanced" ~ 3,
    TRUE ~ NA_real_
  )
}

map_3levels2 <- function(x) {
  dplyr::case_when(
    x == "Never" ~ 1,
    x == "Sometimes" ~ 2,
    x == "Regularly" ~ 3,
    TRUE ~ NA_real_
  )
}

map_2levels <- function(x) {
  x <- ifelse(x == "", 0, 1)
  as.factor(x)
}

survey <- read.csv("../conf/surveydata.csv")
colnames(survey) <- c("iid", "role", "delete3", "roletitle", "delete5", "delete6",
                      "delete7", "delete8", "skilled", "deliver", "excited",
                      "years", "years_pa", "background", "hrqual", "values_soft",
                      "training_soft", "values_tech", "training_tech",
                      "ps_skills", "translation_skills", "delete22", "leading_skills",
                      "communicating_skills", "judging_skills", "assessing_skills", "delete27",
                      "know_ai", "know_cloud", "know_cleaning", "know_engineering", "know_reporting",
                      "know_explanatory", "know_eda", "know_ona", "know_predictive", "delete37", "delete38", 
                      "delete39", "delete40", "delete41", "tech_excel", "tech_julia", "tech_other_opensource", 
                      "tech_other_vendor",
                      "tech_python", "tech_r", "tech_spss", "tech_sql", "delete50")

survey <- survey |> 
  dplyr::select(-starts_with("delete")) |> 
  dplyr::mutate(across(c("skilled", "deliver", "excited", 
                         "values_soft", "training_soft",
                         "values_tech", "training_tech"), map_5levels),
                across(ends_with("skills"), map_3levels1),
                across(starts_with("know"), map_2levels),
                across(starts_with("tech"), map_3levels2),
                across(c("skilled", "deliver", "excited"), 
                       ~ordered(.x, levels = 1:5)),
                across(c("background", "hrqual"), as.factor))
```


```{r, eval = FALSE, echo = FALSE}
map_cat <- function(x) {
  dplyr::case_when(
    x >= 4 ~ 1,
    x < 4 ~ 0,
    TRUE ~ NA_real_
  )
}

survey_cat <- survey |> 
  dplyr::mutate(across(c("skilled", "deliver", "excited"), map_cat))

```

```{r, eval = FALSE, echo = FALSE, message = FALSE, warning = FALSE}
library(effsize)

cohen_survey1 <- survey_cat |> 
  dplyr::select(-iid, -role, -roletitle, -deliver, -excited, -background, -hrqual) |> 
  mutate(across(is.factor, as.numeric))


effectsizes_skilled <- lapply(cohen_survey1[c(2:ncol(cohen_survey1))],
                              function(x) cohen.d(x ~ !cohen_survey1$skilled))


effectsizes_skilled <- data.frame(matrix(unlist(effectsizes_skilled), nrow=length(effectsizes_skilled), byrow=TRUE)) %>% 
  dplyr::mutate(Feature = names(effectsizes_skilled)) %>% 
  dplyr::select(Feature, `Cohen's d` = X3, `Lower 95% CI` = X5, `Upper 95% CI` = X6) %>% 
  dplyr::mutate(across(all_of(c("Cohen's d", "Lower 95% CI", "Upper 95% CI")), as.numeric)) %>% 
  dplyr::mutate(Effect = dplyr::case_when(
    abs(`Cohen's d`) < 0.2 ~ "Very Small/Negligible",
    between(abs(`Cohen's d`), 0.2, 0.5) ~ "Small",
    between(abs(`Cohen's d`), 0.500001, 0.7) ~ "Moderate",
    abs(`Cohen's d`) > 0.7 ~ "Large",
    TRUE ~ "Unknown"
  )) |> 
  dplyr::filter(Effect == "Large") |> 
  dplyr::arrange(-abs(`Cohen's d`)) 

ggplot(data = effectsizes_skilled, aes(x = ordered(Feature, levels = effectsizes_skilled$Feature), y = `Cohen's d`)) +
  geom_bar(fill = "lightblue", stat = "identity") +
  geom_text(aes(label = round(`Cohen's d`, 2)), vjust = -0.2) +
  theme_minimal() +
  theme(axis.text.x = element_text(size = 10, angle = 90, vjust = 0.5, hjust = 1)) +
  labs(x = "Feature",
       title = "Features displaying a large effect size for 'Feeling Skilled'")
```

```{r, eval = FALSE, echo = FALSE, message = FALSE, warning = FALSE}
library(effsize)

cohen_survey2 <- survey_cat |> 
  dplyr::select(-iid, -role, -roletitle, -skilled, -excited, -background, -hrqual) |> 
  mutate(across(is.factor, as.numeric))


effectsizes_deliver <- lapply(cohen_survey2[c(2:ncol(cohen_survey2))],
                              function(x) cohen.d(x ~ !cohen_survey2$deliver))


effectsizes_deliver <- data.frame(matrix(unlist(effectsizes_deliver), nrow=length(effectsizes_deliver), byrow=TRUE)) %>% 
  dplyr::mutate(Feature = names(effectsizes_deliver)) %>% 
  dplyr::select(Feature, `Cohen's d` = X3, `Lower 95% CI` = X5, `Upper 95% CI` = X6) %>% 
  dplyr::mutate(across(all_of(c("Cohen's d", "Lower 95% CI", "Upper 95% CI")), as.numeric)) %>% 
  dplyr::mutate(Effect = dplyr::case_when(
    abs(`Cohen's d`) < 0.2 ~ "Very Small/Negligible",
    between(abs(`Cohen's d`), 0.2, 0.5) ~ "Small",
    between(abs(`Cohen's d`), 0.500001, 0.7) ~ "Moderate",
    abs(`Cohen's d`) > 0.7 ~ "Large",
    TRUE ~ "Unknown"
  )) |> 
  dplyr::filter(Effect == "Large") |> 
  dplyr::arrange(-abs(`Cohen's d`)) 

ggplot(data = effectsizes_deliver, aes(x = ordered(Feature, levels = effectsizes_deliver$Feature), y = `Cohen's d`)) +
  geom_bar(fill = "lightblue", stat = "identity") +
  geom_text(aes(label = round(`Cohen's d`, 2)), vjust = -0.2) +
  theme_minimal() +
  theme(axis.text.x = element_text(size = 10, angle = 90, vjust = 0.5, hjust = 1)) +
  labs(x = "Feature",
       title = "Features displaying a large effect size for 'Delivering Service'")
```

```{r, eval = FALSE, echo = FALSE, message = FALSE, warning = FALSE}
library(effsize)

cohen_survey3 <- survey_cat |> 
  dplyr::select(-iid, -role, -roletitle, -skilled, -deliver, -background, -hrqual) |> 
  mutate(across(is.factor, as.numeric))


effectsizes_excited <- lapply(cohen_survey3[c(2:ncol(cohen_survey3))],
                              function(x) cohen.d(x ~ !cohen_survey3$excited))


effectsizes_excited <- data.frame(matrix(unlist(effectsizes_excited), nrow=length(effectsizes_excited), byrow=TRUE)) %>% 
  dplyr::mutate(Feature = names(effectsizes_excited)) %>% 
  dplyr::select(Feature, `Cohen's d` = X3, `Lower 95% CI` = X5, `Upper 95% CI` = X6) %>% 
  dplyr::mutate(across(all_of(c("Cohen's d", "Lower 95% CI", "Upper 95% CI")), as.numeric)) %>% 
  dplyr::mutate(Effect = dplyr::case_when(
    abs(`Cohen's d`) < 0.2 ~ "Very Small/Negligible",
    between(abs(`Cohen's d`), 0.2, 0.5) ~ "Small",
    between(abs(`Cohen's d`), 0.500001, 0.7) ~ "Moderate",
    abs(`Cohen's d`) > 0.7 ~ "Large",
    TRUE ~ "Unknown"
  )) |> 
  dplyr::filter(Effect == "Large") |> 
  dplyr::arrange(-abs(`Cohen's d`)) 

ggplot(data = effectsizes_excited, aes(x = ordered(Feature, levels = effectsizes_excited$Feature), y = `Cohen's d`)) +
  geom_bar(fill = "lightblue", stat = "identity") +
  geom_text(aes(label = round(`Cohen's d`, 2)), vjust = -0.2) +
  theme_minimal() +
  theme(axis.text.x = element_text(size = 10, angle = 90, vjust = 0.5, hjust = 1)) +
  labs(x = "Feature",
       title = "Features displaying a large effect size for 'Being Excited'")
```
